name: Automated Gig Updater
run-name: ${{ github.actor }} is updating gigs 🚀
on:
  schedule:
    - cron: '7 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Process-Gigs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check for expired gigs
        id: check_expired
        run: |
          current_date=$(date -u +"%Y-%m-%d")
          jq --arg current_date "$current_date" '
            map(select((.endDate | strptime("%b %d, %Y") | mktime) < ($current_date | strptime("%Y-%m-%d") | mktime)))
          ' data/gigs.json > data/expired_gigs.json

          expired_count=$(jq 'length' data/expired_gigs.json)
          if [ "$expired_count" -eq 0 ]; then
            echo "::notice::No gigs to archive"
            echo "found_expired=false" >> $GITHUB_OUTPUT
          else
            echo "::notice::Found expired gigs to archive"
            echo "found_expired=true" >> $GITHUB_OUTPUT
          fi

      - name: Filter gigs and update archive
        if: steps.check_expired.outputs.found_expired == 'true'
        run: |
          current_date=$(date -u +"%Y-%m-%d")
          jq --arg current_date "$current_date" '
            map(select((.endDate | strptime("%b %d, %Y") | mktime) >= ($current_date | strptime("%Y-%m-%d") | mktime)))
          ' data/gigs.json > data/gigs_updated.json

          jq -s '.[0] + .[1]' data/archive.json data/expired_gigs.json > data/archive_updated.json
          mv data/archive_updated.json data/archive.json
          mv data/gigs_updated.json data/gigs.json

          echo "::notice::✅ Archived expired gigs and updated gigs.json."

      - name: Commit and push changes to main branch
        if: steps.check_expired.outputs.found_expired == 'true'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add data/gigs.json data/archive.json
          git commit -m "Remove expired gigs from gigs.json and archive them" || echo "No changes to commit"
          git push
